In [39]:
import numpy as np

1. Vetor

In [57]:
x = np.array([4, 5, 7, 6, 4, 2, 1, 2, 4, 5], dtype=float)
x = [1000, 5000, 2000, 9000, 4, 5, 7, 6, 4, 2, 1, 2, 4, 5]

2. Posição temporal (dado que a variação seja 1)

In [58]:
def get_time_index(x):
    x = np.asarray(x)
    return np.arange(len(x))

In [59]:
t = get_time_index(x)
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

3. Coletar os indices das frequencias

In [60]:
def get_frequency_indices(x):
    x = np.asarray(x)
    N = len(x)

    return np.arange(N // 2 + 1)

In [61]:
k = get_frequency_indices(x)
k

array([0, 1, 2, 3, 4, 5, 6, 7])

4. Transformar cada k em frequência

In [62]:
frequencies  = k / len(x)

In [63]:
frequencies

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       ])