In [45]:
import numpy as np

1. Vetor

In [46]:
x = np.array([4, 5, 7, 6, 4, 2, 1, 2, 4, 5, 1000, 5000, 2000, 9000], dtype=float)

2. Posição temporal (dado que a variação seja 1)

In [47]:
def get_time_index(x):
    x = np.asarray(x)
    return np.arange(len(x))

In [48]:
t = get_time_index(x)
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

3. Coletar os indices das frequencias

In [49]:
def get_frequency_indices(x):
    x = np.asarray(x)
    N = len(x)

    return np.arange(N // 2 + 1)

In [50]:
k = get_frequency_indices(x)
k

array([0, 1, 2, 3, 4, 5, 6, 7])

4. Transformar cada k em frequência

In [51]:
frequencies  = k / len(x)

In [52]:
frequencies

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       ])

5. Onda complexa de fourier

In [53]:
def get_fourier_wave(x, k):
    x = np.asarray(x)

    N = len(x)
    t = np.arange(N)

    wave = np.exp(-2j * np.pi * k * t / N)

    return wave

In [54]:
get_fourier_wave(x, k=1)

array([ 1.        +0.00000000e+00j,  0.90096887-4.33883739e-01j,
        0.6234898 -7.81831482e-01j,  0.22252093-9.74927912e-01j,
       -0.22252093-9.74927912e-01j, -0.6234898 -7.81831482e-01j,
       -0.90096887-4.33883739e-01j, -1.        -1.22464680e-16j,
       -0.90096887+4.33883739e-01j, -0.6234898 +7.81831482e-01j,
       -0.22252093+9.74927912e-01j,  0.22252093+9.74927912e-01j,
        0.6234898 +7.81831482e-01j,  0.90096887+4.33883739e-01j])

In [55]:
import numpy as np

x = np.array([4, 5, 7, 6], dtype=float)

N = len(x)
t = np.arange(N)

k = 1

wave = np.exp(-2j * np.pi * k * t / N)

In [56]:
contributions = x * wave

In [57]:
contributions

array([ 4.00000000e+00+0.00000000e+00j,  3.06161700e-16-5.00000000e+00j,
       -7.00000000e+00-8.57252759e-16j, -1.10218212e-15+6.00000000e+00j])

In [58]:
def fourier_coefficient(x, k):
    x = np.asarray(x, dtype=float)

    N = len(x)
    t = np.arange(N)

    wave = np.exp(-2j * np.pi * k * t / N)

    return np.sum(x * wave)

In [59]:
def fourier_coefficients(x):
    x = np.asarray(x, dtype=float)

    N = len(x)
    t = np.arange(N)
    k_values = np.arange(N // 2 + 1)

    coefficients = []

    for k in k_values:
        wave = np.exp(-2j * np.pi * k * t / N)
        X_k = np.sum(x * wave)

        coefficients.append(X_k)

    return np.array(coefficients)

In [60]:
coefficients = fourier_coefficients(x)

In [61]:
magnitude = np.abs(coefficients) 
power = magnitude ** 2

In [62]:
power

array([4.84000000e+02, 1.00000000e+01, 1.21480542e-30])

In [63]:
real = coefficients.real
imag = coefficients.imag

power = real**2 + imag**2

In [64]:
power

array([4.84000000e+02, 1.00000000e+01, 1.21480542e-30])